version: "3.8"
services:

  pgdb:
    image: postgres
    container_name: studypaldb
    environment:
      - POSTGRES_DB=studypaldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=c3po
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data     
    restart: unless-stopped


  web:
    build: .  
    container_name: studypal
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/studypal
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - xray-daemon
    environment:
      - DATABASE_URL=postgres://postgres:c3po@db:5432/studypal
      - OTEL_SERVICE_NAME=studypal
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT="https://api.honeycomb.io"
      - OTEL_EXPORTER_OTLP_HEADERS="x-honeycomb-team=J0CNOIywMr5R3ACl9HKwyA"
    restart: unless-stopped

  xray-daemon:
    image: "amazon/aws-xray-daemon"
    container_name: xray-daemon
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: "us-east-1"
    command: 
      - "xray -o -b 0.0.0.0:2000" 
    ports:
      - "2000:2000/udp"
   
  redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheusstudypal
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - C:/Users/cfaki/OneDrive/Eneokazi/StudyPal/prometheus.yml:/etc/prometheus/prometheus.yml #replace with the absolute path to your prometheus file.

    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafanastudypal
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

    restart: unless-stopped

  
volumes:
  postgresql-data:
    driver: local



# docker exec -it <container_name_or_id> bash
# psql -U postgres    

# CREATE DATABASE studypaldb;
# CREATE USER postgres WITH PASSWORD 'c3po';
# GRANT ALL PRIVILEGES ON DATABASE studypaldb TO postgres;
# \q

# docker-compose up --build
# docker-compose up --force-recreate
# docker-compose build --no-cache

#DEBUGGING

#For checking logs and debugging
# docker logs [containername]

# Grafana access - http://localhost:3000

