name: studypal

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]


env:
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
  AWS_DEFAULT_REGION: "us-east-1"
 
        
# jobs: 
#     build-and-push:
#         runs-on: ubuntu-latest
#         name: Studypal EC2 Deployment

#         steps:
#             - name: Checkout code 
#               uses: actions/checkout@v2  

#             - name: Login to Docker Hub
#               uses: docker/login-action@v1
#               with:
#                 username: ${{secrets.DOCKER_USERNAME}}
#                 password: ${{secrets.DOCKER_PASSWORD}}  

#             - name: Building the Docker Image
#               run: docker build -t tonnykioko/studypal:latest .
            
#             - name: Pushing Image to Docker Hub
#               run: docker push tonnykioko/studypal:latest

    

#             ## Running on AWS EC2
#             - name: Deployment to AWS
#               uses: appleboy/ssh-action@master
#               with: 
#                 host: ${{secrets.AWS_IP_ADDRESS}}
#                 username: ${{secrets.AWS_USER_NAME}}
#                 key: ${{secrets.AWS_SSH_KEY}}
#                 script: |
#                     docker pull tonnykioko/studypal:latest
#                     docker stop studypalapp || true
#                     docker rm studypalapp || true
#                     docker run -d -p 8000:8000 --name studypalapp tonnykioko/studypal:latest

            
            ## Running Serverless on AWS Fargate

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Studypal Fargate Deployment

    steps:
      - name: Checkout repository
        uses:  actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Image to ECR
        run:  |
          docker build --no-cache -t ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_DEFAULT_REGION}}.amazonaws.com/studypal:latest .
          docker push ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_DEFAULT_REGION}}.amazonaws.com/studypal:latest

      - name: Deploying Studypal to Fargate
        run: |
          aws ecs update-service  --cluster studypalcluster  --service studypalservice  --forcee-new-deployment
      


