name: studypal

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

        
jobs: 
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code 
              uses: actions/checkout@v2
            
            - name: Setting up Docker build
              uses: docker/setup-buildx-action@v1
            
            - name: Building Docker Image
              run:  docker build --file Dockerfile --tag ghcr.io/${{ github.Tonny-Kioko}}/StudyPal:${{ github.sha }} .

            - name: Logging into GitHub COntainer Registry
              run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.Tonny-Kioko}} --password-stdin

            - name: Pushing the Docker Image
              run: docker push ghcr.io/${{ github.Tonny-Kioko }}/studypal:${{ github.sha }}
